# Generated by Django 6.0.1 on 2026-02-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type_scope',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default='Expense', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=20),
        ),
    ]
