# Generated by Django 6.0.1 on 2026-02-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_riskalert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_in_gbp',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True, verbose_name='Amount (GBP)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='occurred_at',
            field=models.DateTimeField(verbose_name='Occurred at'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Original amount'),
        ),
    ]
