# Generated by Django 5.2.12 on 2026-03-16 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0011_remove_emailotp_finance_ema_email_477bc6_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskalert",
            name="transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="risk_alert",
                to="finance.transaction",
            ),
        ),
    ]
